#!/bin/zsh

export M_PREFIX=/Applications/Maxima.app/Contents/Resources/opt;
export PYTHONPATH=${M_PREFIX}/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/:$PYTHONPATH;
export MANPATH=${M_PREFIX}/share/man:$MANPATH;
export PATH=${M_PREFIX}/bin:$PATH;

rmaxima;
